### ISSUE TITLE
Bird's eye view for an application flow

### ISSUE THREAD

**Issue by otsakir** [Mobicents/RestComm#168]
Provide an image or pdf representation of an application flow. Modules or steps could be used as nodes and, actions as links between them and module labels and <say> phrases as text.

**Comment by deruelle** [comment]
Interesting similarities with http://www.twhello.com/

**Comment by gvagenas** [comment]
Guys, I merged pull 368 for this issue, can we close this ?

**Comment by otsakir** [comment]
Not yet @gvagenas , there is still some reviewing and testing that needs to be done.

**Comment by gvagenas** [comment]
Sorry, I rushed to merge the pull request. I will revert this

**Comment by brainslog** [comment]
@otsakir what is missing on this ? I can see it's still not present in master.

**Comment by otsakir** [comment]
@deruelle, the following pieces are missing:
 - Understand ES "mapped" routing and use with linking modules that are targeted by it.
 - Remove "dynamic" routing support from the designer. It will be grayed out and won't allow saving. It will still work when running an application.
 - Display a warning when displaying graphs where dynamic routing is used. 
 - testing.

**Comment by deruelle** [comment]
Where do we stand on this ?

**Comment by otsakir** [comment]
Correction: 

 - "mapped" routing links are displayed just fine
 - we could live with dynamic routing support 
 - we do need to display a warning in the graph where dynamic routing is used
 - manual testing
